name: 'JSON File Transform With Graceful Encoding Handling'
description: 'Modify fields in a JSON file after ensuring that the encoding is correct'
branding:
  icon: 'edit'
  color: 'green'
inputs:
  files:
    description: 'The JSON file(s) to modify'
    required: true
  follow-symbolic-links:
    description: 'Whether to follow symbolic links when resolving files'
    required: false
    default: true
  key-value-pairs:
    description: 'The key-value pairs to modify'
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'
