name: Test

on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md

  pull_request:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md

  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        name: Checkout code

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"
          cache-dependency-path: package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Test
        run: npm test